from linked_lists import SinglyLinkedList, DoublyLinkedList, max, min

''''Singly Linked List'''

linked = SinglyLinkedList()
linked.insert(0)
linked.insert(1)
linked.append(2)
print(linked)
print(linked.pop())
linked.insert_index(1,2)
linked.insert_index(2,3)
print(linked)
print(linked.remove())
print(linked)
linked.append(1)
linked.insert(1)
linked.append(2)
print(linked)
print(linked.count(1))
print(f'Value: {linked.index(0)}')
print(f"Index: {linked.value(linked.index(0))}")
print(linked.remove_index(1))
print(linked)
linked.insert_index(1,0)
print(linked)
print(max(linked))
print(min(linked))
other_linked = SinglyLinkedList(linked)
print("Copy Linked List: " + repr(other_linked))
other_linked.remove()
other_linked.insert(2)
print("Copy Linked List: " + repr(other_linked))
print("Original Linked List: " + repr(linked))
print("Join: " + repr(SinglyLinkedList.join(linked, other_linked)))
print()

''''Doubly Linked List'''

doubly = DoublyLinkedList()
doubly.insert(0)
doubly.insert(1)
doubly.append(-1)
doubly.append(-2)
print(doubly)
print(doubly.pop())
print(doubly.remove())
print(repr(doubly))
doubly.insert(1)
doubly.append(-2)
print(doubly)
print(f'Value 1 is at index {doubly.index(1)}')
print(f'Object in index 2 is {doubly.value(2)}')
print(doubly.remove_index(2))
print(doubly.remove_index(1))
print(repr(doubly))
doubly.insert_index(1,-3)
print(doubly)
doubly.insert_index(2,2)
print(doubly)
print(max(doubly))
print(min(doubly))
print(doubly)
doubly.pop()
print(doubly)
print(f'Middle Value: {DoublyLinkedList.middle_value(doubly)}')
print(f'Middle Index: {DoublyLinkedList.middle_index(doubly)}')
other_doubly = DoublyLinkedList.join(doubly,doubly)
print(f"Other Doubly Linked List: {repr(other_doubly)}")
other_doubly.replace_all(-3,0)
print(f"Other Doubly Linked List: {repr(other_doubly)}")
print(f'Lenght of Other Doubly Linked List: {len(other_doubly)}')
print(f'Middle Value: {DoublyLinkedList.middle_value(other_doubly)}')
print(f'Middle Index: {DoublyLinkedList.middle_index(other_doubly)}')
print(f'Last index of value 1 is {other_doubly.last_index(1)}')
print(f'0 appears {other_doubly.count(0)} times')
other_doubly.replace_value(3,-1)
other_doubly.replace_value(5,-2)
print(f"Other Doubly Linked List: {repr(other_doubly)}")
convert = DoublyLinkedList([1,2,3,4,5]) 
print(f'Converted into Doubly Linked List: {repr(convert)}')
copy = DoublyLinkedList.copy(convert)
print(f'Copy Doubly Linked List: {repr(copy)}')