from linked_lists import SinglyLinkedList, max, min

linked = SinglyLinkedList()
linked.insert(0)
linked.insert(1)
linked.append(2)
print(linked)
print(linked.pop())
print(linked)
print(linked.remove())
print(linked)
linked.append(1)
linked.insert(1)
linked.append(2)
print(linked)
print(linked.count(1))
print(linked.index_value(0))
print(linked.remove_index(1))
print(linked)
linked.insert_index(1,0)
print(linked)
print(max(linked))
print(min(linked))
other_linked = SinglyLinkedList(linked)
print("Copy Linked List: " + repr(other_linked))
other_linked.remove()
other_linked.insert(2)
print("Copy Linked List: " + repr(other_linked))
print("Original Linked List: " + repr(linked))
print("Join: " + repr(SinglyLinkedList.join(linked, other_linked)))