from my_vector import MyArray
from time import time

array = MyArray()
array.fill_array_randomly()
print("First array:")
print(array)
array.append(1)
print(repr(array))
array.insert(0,0)
print(repr(array))
print(f"Element 3 appeared {array.count(3)} time(s).")
print(f"The {array.pop()} element has been removed.")
print(f"The index of element 5 is {array.index(5)}.")
print(array)
print("Trying to remove element 2...")
print(array.remove(2))
print(array)
other_array = MyArray(20)
other_array.fill_array_randomly()
print("Other array:")
print(other_array)
array.extend(other_array)
print("Extending the array with other iterables...")
print(array)
print(f"Size of extended array: {len(array.data)}")
print("Adjusting...")
array.adjust()
print(f"Size of adjusted array: {len(array.data)}")
array1 = MyArray()
array1.extend([1,2,3,4,5,6,7,8,9,10])
array2 = MyArray()
array2.extend([1,2,3,4,5,6,7,8,9,10])
print(f"Checking if array1 is equal to array2: {array1 == array2}")
print(f"Checking if array1 is equal to array1: {array1 == array1}")
big_array = MyArray(10000)
print("Big array:")
big_array.fill_array_randomly()
print("Selection sort:")
start = time()
big_array.selection_sort()
end = time()
print(f"Duration: {end - start:.4f} secs.")
big_array.fill_array_randomly()
print("Insertion sort:")
start = time()
big_array.insertion_sort()
end = time()
print(f"Duration: {end - start:.4f} secs.")
big_array.fill_array_randomly()
print("Bubble sort:")
start = time()
big_array.bubble_sort()
end = time()
print(f"Duration: {end - start:.4f} secs.")
big_array.fill_array_randomly()
print("Quick sort:")
start = time()
big_array.quick_sort()
end = time()
print(f"Duration: {end - start:.4f} secs.")
big_array.fill_array_randomly()
print("Merge sort:")
start = time()
big_array.merge_sort()
end = time()
print(f"Duration: {end - start:.4f} secs.")