from linked_lists import SinglyLinkedList, DoublyLinkedList, CircularLinkedList, max, min

''''Singly Linked List'''

linked = SinglyLinkedList()
linked.insert(0)
linked.insert(1)
linked.append(2)
print(linked)
print(linked.pop())
linked.insert_index(1,2)
linked.insert_index(2,3)
print(linked)
print(linked.remove())
print(linked)
linked.append(1)
linked.insert(1)
linked.append(2)
print(linked)
print(linked.count(1))
print(f'Value: {linked.index(0)}')
print(f"Index: {linked.value(linked.index(0))}")
print(linked.remove_index(1))
print(linked)
linked.insert_index(1,0)
print(linked)
print(max(linked))
print(min(linked))
other_linked = SinglyLinkedList(linked)
print("Copy Linked List: " + repr(other_linked))
other_linked.remove()
other_linked.insert(2)
print("Copy Linked List: " + repr(other_linked))
print("Original Linked List: " + repr(linked))
print("Join: " + repr(SinglyLinkedList.join(linked, other_linked)))
print()

''''Doubly Linked List'''

doubly = DoublyLinkedList()
doubly.insert(0)
doubly.insert(1)
doubly.append(-1)
doubly.append(-2)
print(doubly)
print(doubly.pop())
print(doubly.remove())
print(repr(doubly))
doubly.insert(1)
doubly.append(-2)
print(doubly)
print(f'Value 1 is at index {doubly.index(1)}')
print(f'Object in index 2 is {doubly.value(2)}')
print(doubly.remove_index(2))
print(doubly.remove_index(1))
print(repr(doubly))
doubly.insert_index(1,-3)
print(doubly)
doubly.insert_index(2,2)
print(doubly)
print(max(doubly))
print(min(doubly))
print(doubly)
doubly.pop()
print(doubly)
print(f'Middle Value: {DoublyLinkedList.middle_value(doubly)}')
print(f'Middle Index: {DoublyLinkedList.middle_index(doubly)}')
other_doubly = DoublyLinkedList.join(doubly,doubly)
print(f"Other Doubly Linked List: {repr(other_doubly)}")
other_doubly.replace_all(-3,0)
print(f"Other Doubly Linked List: {repr(other_doubly)}")
print(f'Lenght of Other Doubly Linked List: {len(other_doubly)}')
print(f'Middle Value: {DoublyLinkedList.middle_value(other_doubly)}')
print(f'Middle Index: {DoublyLinkedList.middle_index(other_doubly)}')
print(f'Last index of value 1 is {other_doubly.last_index(1)}')
print(f'0 appears {other_doubly.count(0)} times')
other_doubly.replace_value(3,-1)
other_doubly.replace_value(5,-2)
print(f"Other Doubly Linked List: {repr(other_doubly)}")
convert = DoublyLinkedList([1,2,3,4,5]) 
print(f'Converted into Doubly Linked List: {repr(convert)}')
copy = DoublyLinkedList.copy(convert)
print(f'Copy Doubly Linked List: {repr(copy)}')
print()

''''Circular Linked List'''

circular = CircularLinkedList()
circular.insert(0)
circular.insert(1)
circular.insert(2)
circular.append(-1)
circular.append(-2)
print(circular)
print(f"Lenght: {len(circular)}")
print(f"Value {circular.remove()} has been removed")
print(f"Value {circular.pop()} has been removed")
print(f"Value {circular.pop()} has been removed")
print(circular)
circular.append(1)
print(circular)
print(f"Value 1 appears {circular.count(1)} times")
print(f"Index of value 0 is {circular.index(0)}")
print(f"Last index of value 1 is {circular.last_index(1)}")
print(f"Value of index 1 is {circular.value(1)}")
circular.replace_all(1,2)
print(circular)
circular.replace_value(1,1)
print(circular)
circular.clear()
print(circular)
circular.append(1)
circular.append(2)
circular.append(1)
print(f"New Circular Linked List: {repr(circular)}")
print(f"Value {circular.remove_index(1)} of index 1 has been removed")
print(circular)
circular.insert_index(1,0)
print(circular)
circular.insert(2)
circular.insert(3)
print(circular)
print(f"Greatest value is {max(circular)}")
print(f"Lowest value is {min(circular)}")
print(f"Middle value is {CircularLinkedList.middle_value(circular)}")
print(f"Middle index is {CircularLinkedList.middle_index(circular)}")
other_circular = CircularLinkedList.copy(circular)
print(f"Other Circular Linked List: {repr(other_circular)}")
join = CircularLinkedList.join(circular, other_circular) # type: ignore
print(f"Join Circular Linked List: {repr(join)}")
iterable = CircularLinkedList([1,2,3,4,5])
print(f"Converted to Circular Linked List: {repr(iterable)}")
array = CircularLinkedList.to_list(iterable)
print(f"Converted to list: {array}")
print(f"Have already been created {iterable.instances} instances of CircularLinkedList")
